### PR TITLE
More tests and custom datatypes

### LINKED ISSUE #42: Name is null for PrimitiveTypes
See, for example, this string:

```json
{
    "children": [
    ],
    "concept": {
        "key": "PrimitiveType",
        "language": "LIonCore-M3",
        "version": "1"
    },
    "id": "LIonCore-builtins-String",
    "parent": "LIonCore-builtins",
    "properties": [
        {
            "property": {
                "key": "IKeyed-key",
                "language": "LIonCore-M3",
                "version": "1"
            },
            "value": "LIonCore-builtins-String"
        },
        {
            "property": {
                "key": "LIonCore-builtins-INamed-name",
                "language": "LIonCore-builtins",
                "version": "1"
            },
            "value": null
        }
    ],
    "references": [
    ]
}
```

### PR DESCRIPTION
**Pull request by enikao**
Added `Sorted` variants of `SerializedNode` et al. to make comparison easier in tests.

Added more tests:
* JSON <-> M3
* JSON <-> SLanguage

Should fix #42, #43

### CODE REVIEW

**Comment by enikao** [comment]
@woppa684 Does this address your issues?

**Comment by enikao** [comment]
@ftomassetti Maybe we want to move the `Sorted` classes to LW-Java?

**Comment by woppa684** [comment]
> @woppa684 Does this address your issues?

Hard to tell, I don't really know how to review these changes. Any suggestions?

**Comment by enikao** [comment]
> > @woppa684 Does this address your issues?
> 
> Hard to tell, I don't really know how to review these changes. Any suggestions?

Check out the branch locally, or look at the serialized examples (e.g. https://github.com/LIonWeb-org/lioncore-mps/pull/49/files#diff-6941bbdb05685ade5b0849ee331d4c20c14de0e2c0f88bdd2d119a04b8b16029 )

**Comment by ftomassetti** [comment]
> @ftomassetti Maybe we want to move the `Sorted` classes to LW-Java?

Do you mean SortedSerializedNode and the siblings?
Are they used to facilitate comparisons? Or for something else?

If they are use to facilitate comparisons, for that I have a class to perform comparison (ModelComparator) but I do that at the node level, not at the SerializedNode level.
Why do we need to do that to the SerializedNode level?

**Comment by enikao** [comment]
> If they are use to facilitate comparisons, for that I have a class to perform comparison (ModelComparator) but I do that at the node level, not at the SerializedNode level. Why do we need to do that to the SerializedNode level?

Fits better how I handle stuff inside MPS -- I mostly work with SerializedNodes.

**Pull request merged**
