### PR TITLE
special handling of BaseConcept properties in M1 converter

### PR DESCRIPTION
**Pull request by enikao**

### CODE REVIEW

**Comment by dslmeinte** [comment]
Couple of remarks:

- I don't get the `lionweb-mps` project to build. No idea why not (yet).
- I don't really get why `IJsonBuiltins` extends `IJsonBuiltins_2023_1`. Maybe a little more documentation would help?

For the sake of making a model (=instance-level) export, I'm happy to approve. Let's look into the non-building as well?

**Review by dslmeinte — APPROVED** [review]

**Comment by enikao** [comment]
>  I don't get the `lionweb-mps` project to build. No idea why not (yet).

Strange, the build server is successful. Let's have a look together.

> I don't really get why `IJsonBuiltins` extends `IJsonBuiltins_2023_1`. Maybe a little more documentation would help?

The idea is to keep some kind of versioning history: `IJsonBuiltins-2023.1` -> `IJsonBuiltins-2024.1` -> `IJsonBuiltins-2024.2` -> `IJsonBuiltins` ( suffix `-current` omitted). The assumption is our version changes are only additive. Not sure whether that would work out, let's see (-:

**Comment by dslmeinte** [comment]
> > I don't really get why `IJsonBuiltins` extends `IJsonBuiltins_2023_1`. Maybe a little more documentation would help?
> 
> The idea is to keep some kind of versioning history: `IJsonBuiltins-2023.1` -> `IJsonBuiltins-2024.1` -> `IJsonBuiltins-2024.2` -> `IJsonBuiltins` ( suffix `-current` omitted). The assumption is our version changes are only additive. Not sure whether that would work out, let's see (-:

I got that part, so I guess it's the name of the thing I don't get. Could the name reflect the fact that it's meant to be the LionCore built-ins **plus** what you get from `BaseConcept`?

**Comment by enikao** [comment]
> I got that part, so I guess it's the name of the thing I don't get. Could the name reflect the fact that it's meant to be the LionCore built-ins **plus** what you get from `BaseConcept`?

I agree, something like `IJsonConstants` (symmetric to `ILionCoreConstants`) would be better.

**Review by dslmeinte — APPROVED** [review]

**Pull request merged**
