### PR TITLE
optionally export computed properties to LW JSON

### PR DESCRIPTION
**Pull request by enikao**

### CODE REVIEW

**Review by dslmeinte — APPROVED** [review]
The `Either` type is a bit weirdly-named: I'd expect is to be named `Maybe` (with `NONE` instead of `EMPTY`), although there's then no corresponding `Some` subtype (nor does there absolutely have to be one).

**Comment by dslmeinte** [comment]
`Option` instead of `Maybe` would also work, and might be more Java-like, but doesn't really matter.

**Comment by enikao** [comment]
There is an `java.util.Optional` type, but it has different semantics (_empty_ if `null`). I don't want to confuse them.

**Comment by dslmeinte** [comment]
> There is an `java.util.Optional` type, but it has different semantics (_empty_ if `null`). I don't want to confuse them.

Exactly, so `Maybe` is fine.

**Pull request merged**
