### PR TITLE
Update lionweb-java

### PR DESCRIPTION
**Pull request by enikao**
Should also get us the latest json format.

### CODE REVIEW

**Comment by enikao** [comment]
We're already using the new json format, but some classes still have the old name (https://github.com/LIonWeb-org/lioncore-java/issues/78, https://github.com/LIonWeb-org/lioncore-java/issues/77, https://github.com/LIonWeb-org/lioncore-java/issues/76)

**Comment by ftomassetti** [comment]
I just released lioncore-java 0.0.24, so that the classes have the right names

**Comment by enikao** [comment]
> I just released lioncore-java 0.0.24, so that the classes have the right names

Thanks a lot

**Comment by ftomassetti** [comment]
Thank you and sorry for missing the renames before

**Pull request merged**
