### PR TITLE
export MPS Concept alias/shortDescription to LW JSON annotation

### PR DESCRIPTION
**Pull request by enikao**
depends on https://github.com/LionWeb-io/lionweb-java/pull/142

### CODE REVIEW

**Comment by dslmeinte** [comment]
I’m guessing this requires (the publication of) `lionweb-java` version 0.2.14, so I'll review after that's been published.

**Comment by ftomassetti** [comment]
lionweb-java 0.2.14 has been released earlier today (so I tried re-starting the checks)

**Comment by dslmeinte** [comment]
OK, I updated the `gradle.properties` to not have `-SNAPSHOT` after `0.2.14`, but then I still get some compile errors. I think the latest commit on `lionweb-java` hasn't been propagated yet.

Shall I try and fix those? They're probably renames.

**Comment by dslmeinte** [comment]
At http://127.0.0.1:63320/node?ref=f%3Adiff_new%23r%3A6239253d-0ab2-49c2-bcf4-81f1b9a92f3e%28io.lionweb.mps.json.language%40new%29%2F3546057254294704083, `addDescription` seems to do two things:

1. Introspect on the passed `mps` thingy.
2. Add an annotation to the passed `lw` classifier with some info obtained from step 1.

Can we make that split explicit?

**Review by dslmeinte — APPROVED** [review]
Question left as comment https://github.com/LionWeb-io/lionweb-mps/pull/94#issuecomment-2135303866

**Comment by enikao** [comment]
> At http://127.0.0.1:63320/node?ref=f%3Adiff_new%23r%3A6239253d-0ab2-49c2-bcf4-81f1b9a92f3e%28io.lionweb.mps.json.language%40new%29%2F3546057254294704083

This url links to the temporary diff model, do you have the real one?

**Comment by dslmeinte** [comment]
> This url links to the temporary diff model, do you have the real one?

This works?:

http://127.0.0.1:63320/node?ref=r%3A6239253d-0ab2-49c2-bcf4-81f1b9a92f3e%28io.lionweb.mps.json.language%29%2F3546057254294704083

**Review by dslmeinte — APPROVED** [review]

**Pull request merged**
