### PR TITLE
Filter nodes of abstract concepts or interfaces from exporting to LionWeb JSON

### LINKED ISSUE #92: Exclude instances of abstract concepts from M1 export
MPS allows to instantiate abstract concepts or interfaces, but LionWeb doesn't.
We should filter these instances from export.

### PR DESCRIPTION
**Pull request by enikao**
Fixes #92

### CODE REVIEW

**Comment by dslmeinte** [comment]
In http://127.0.0.1:63320/node?ref=r%3A677983a1-6578-432d-8175-68c906e0375c%28io.lionweb.mps.json%29%2F3546057254282289424 : Is there a possibility to DRY the repeated single-method interface implementation?

**Review by dslmeinte — COMMENTED** [review]
See 1 question in Conversation comments

**Review by dslmeinte — APPROVED** [review]
(wanted to Approve)

**Comment by enikao** [comment]
> In http://127.0.0.1:63320/node?ref=r%3A677983a1-6578-432d-8175-68c906e0375c%28io.lionweb.mps.json%29%2F3546057254282289424 : Is there a possibility to DRY the repeated single-method interface implementation?

Fixed

**Pull request merged**
